<a href="https://colab.research.google.com/github/santiagoadiaz2108/CienciaDeDatos/blob/main/Numpy_Carolina_y_Santiago.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Crear un arreglo unidimensional (vector)
vector = np.array([10, 20, 30, 40, 50])
print("Vector:", vector)

# Crear un arreglo bidimensional (matriz)
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\nMatriz:\n", matriz)


Vector: [10 20 30 40 50]

Matriz:
 [[1 2 3]
 [4 5 6]]


In [ ]:
#2 Propiedades

print("Dimensiones del vector:", vector.ndim)
print("Forma de la matriz:", matriz.shape)
print("Tamaño total de la matriz:", matriz.size)
print("Tipo de dato del vector:", vector.dtype)


Dimensiones del vector: 1
Forma de la matriz: (2, 3)
Tamaño total de la matriz: 6
Tipo de dato del vector: int64


In [ ]:
# 3 Arreglos

# Arreglo de ceros
cero = np.zeros((3, 3))
print("\nMatriz de ceros:\n", cero)

# Arreglo de unos
unos = np.ones((2, 4))
print("\nMatriz de unos:\n", unos)

# Números del 0 al 9
rango = np.arange(0, 10)
print("\nArreglo con arange:", rango)

# Números del 0 al 1 con salto de 0.2
decimales = np.arange(0, 1.1, 0.2)
print("\nArreglo decimales:", decimales)



Matriz de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriz de unos:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Arreglo con arange: [0 1 2 3 4 5 6 7 8 9]

Arreglo decimales: [0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
#Operaciones matemáticas

a = np.array([2, 4, 6, 8])
b = np.array([1, 1, 1, 1])

print("\nSuma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)
print("División:", a / 2)
print("Potencia:", a ** 2)



Suma: [3 5 7 9]
Resta: [1 3 5 7]
Multiplicación: [2 4 6 8]
División: [1. 2. 3. 4.]
Potencia: [ 4 16 36 64]


In [ ]:
#Funciones

datos = np.array([12, 18, 25, 30, 45, 50])

print("\nPromedio:", np.mean(datos))
print("Máximo:", np.max(datos))
print("Mínimo:", np.min(datos))
print("Desviación estándar:", np.std(datos))



Promedio: 30.0
Máximo: 50
Mínimo: 12
Desviación estándar: 13.650396819628847
